### PR TITLE
Styling: changed website title. added a favicon.

### PR DESCRIPTION
**Pull request by msong1**

### CODE REVIEW

**Review by NicMilli — CHANGES_REQUESTED** [review]
Looks good but you deleted the logo from the Navbar

**Comment by msong1** [comment]
I just moved the importing line down so that it loads after loading Redux, so it still loads the logo properly.

**Comment by B-Tanonaka** [comment]
RelatedItemsPhotos

**Comment by B-Tanonaka** [comment]
Modal

**Review by NicMilli — APPROVED** [review]
Looks good!

**Comment by msong1** [comment]
answer-modal
question-modal
leaving images here to use in readme

**Comment by msong1** [comment]
leaving a comment to upload QnA photo for readme
QnAPhotos

**Pull request merged**
